<a href="https://colab.research.google.com/github/seongs/pytorch/blob/main/%ED%85%90%EC%84%9C(Tensor).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#텐서(TENSOR)
- 텐서(tensor)는 배열(array)이나 행렬(matrix)와 매우 유사한 특수한 특수한 자료구조입니다. PyTorch에서는 텐서를 사용하여 모델의 입력(input)과 출력(output), 그리고 모델의 매개변수들을 부호화(encode)합니다.

- 텐서는 GPU나 다른 하드웨어 가속기에서 실행할 수 있다는 점만 제외하면 Numpy의 ndarray와 유사합니다. 실제오 텐서와 NumPy 배열(array)은 종종 동일한  (내부)underly 메모리를 공유할 수 있어 데이터를 복사할 필요가 없습니다. 텐서는 또한 자동미분(automatic differntiation)에 최적화되어 있습니다. ndarray에 익숙하다면 Tensor API를 바로 사용할 수 있을 것 입니다.

In [ ]:
import torch
import numpy as np

## 텐서(tensor) 초기화
- 텐서는 여러가지 방법으로 초기화할 수 있습니다. 다음 예를 살펴보세요:

**데이터로부터 직접 생성하기**

데이터로 부터 직접 텐서를 생성할 수 있습니다. 데이터의 자료형은 자동으로 유추합니다.

In [ ]:
data = [[1,2],[3,4]]
x_data = torch.tensor(data)

**NumPy 배열로 부터 생성하기**

텐서는 NumPy 배열로 생성할 수 있습니다. (그 반대도 가능합니다.)



In [ ]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)

**다른 텐서로부터 생성하기:**
명시적으로 재정의하지 않는다면, 인자로 주어진 텐서의 속성(shape, datatype)을 유지합니다.

In [ ]:
x_ones = torch.ones_like(x_data)
print(f"Ones Tensor: \n {x_ones} \n")

x_rand = torch.rand_like(x_data, dtype = torch.float)
print(f"Random Tensor \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]]) 

Random Tensor 
 tensor([[0.1185, 0.1603],
        [0.4023, 0.1244]]) 



**random 또는 constant 값을 사용하기:**

shape은 텐서의 dimension을 나타내는 튜플로, 아래 함수들에서는 출력 텐서의 차원을 결정합니다.

In [ ]:
shape = (2,3,)
rand_tensor  = torch.rand(shape)
ones_tensor  = torch.ones(shape)
zeros_tensor = torch.zeros(shape)

print(f"Random Tensor: \n {rand_tensor} \n")
print(f"Ones Tensor: \n {ones_tensor} \n")
print(f"Zeros Tensor: \n {zeros_tensor} \n")

Random Tensor: 
 tensor([[0.4214, 0.5545, 0.8700],
        [0.0565, 0.2336, 0.1652]]) 

Ones Tensor: 
 tensor([[1., 1., 1.],
        [1., 1., 1.]]) 

Zeros Tensor: 
 tensor([[0., 0., 0.],
        [0., 0., 0.]]) 



## 텐서의 속성

- 텐서의 속성은 텐서의 shape, datatype 및 어느 장치에 저장되는지를 나타냅니다.

In [ ]:
tensor = torch.rand(3,4)

print(f"Shape of tensor: {tensor.shape}")
print(f"Datatype of tensro: {tensor.dtype}")
print(f"Device tensor is stored on: {tensor.device}")

Shape of tensor: torch.Size([3, 4])
Datatype of tensro: torch.float32
Device tensor is stored on: cpu


## 텐서의 연산
- transposing, indexing, slicing, 수학계산, 선형대수, random sampling 등, 100가지 이상의 텐서연산들을 [여기](https://pytorch.org/docs/stable/torch.html)에서 확인할 수 있습니다. 각 연산들을 GPU에서 실행힐 수 있습니다.

기본적으로 텐서는 CPU에 생성됩니다. .to 메소드를 사용하면 GPU로 텐서를 명시적으로 이동할 수 있습니다. 장치들 간에 큰 텐서들을 복사하는 것은 시간과 메모리 측면에서 비용이 많이든다는 것을 기억하세요

In [ ]:
if torch.cuda.is_available():
  tensor = tensor.to("cuda")

**NumPy식의 표준 인덴싱과 슬라이싱:**

In [ ]:
tensor = torch.ones(4,4)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[...,-1]}")
tensor[:,1] = 0
print(tensor)

First row: tensor([1., 1., 1., 1.])
First column: tensor([1., 1., 1., 1.])
Last column: tensor([1., 1., 1., 1.])
tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])


 텐서 합치기 torch.cat을 사용하여 주어진 차원에 따라 텐서을 연결할 수 있습니다. torch.stack도 참고해보세요

In [ ]:
t1 = torch.cat([tensor, tensor, tensor],dim=1)
print(t1)

tensor([[1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.],
        [1., 0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1.]])


In [ ]:
t2 = torch.stack([tensor, tensor, tensor],dim=1)
print(t2)

tensor([[[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]],

        [[1., 0., 1., 1.],
         [1., 0., 1., 1.],
         [1., 0., 1., 1.]]])


**산술연산**

In [ ]:
y1 = tensor @ tensor.T
y2 = tensor.matmul(tensor.T)

y3 = torch.rand_like(y1)
torch.matmul(tensor, tensor.T, out=y3)

z1 = tensor * tensor
z2 = tensor.mul(tensor)

z3 =  torch.rand_like(tensor)
torch.mul(tensor, tensor, out=z3)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]])

단일-요소(single-element) 텐서 텐서의 모든 값을 하나로 집계(aggregate)하여 요소가 하나인 텐서의 경우, item() 을 사용하여 Python 숫자 값으로 변환할 수 있습니다:

In [ ]:
agg = tensor.sum()
agg_item = agg.item()
print(agg_item, type(agg_item))

12.0 <class 'float'>


in-place연산 결과를 피연산자에 저장하는 연산을 바꿔치기 연산이라고 부르며 _ 접미살를 갖습니다. 예를 들어: x_copy나 x.t_()를 변경합니다.

In [ ]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.],
        [1., 0., 1., 1.]]) 

tensor([[6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.],
        [6., 5., 6., 6.]])


## NumPy 변환(Bridge)
- CPU 상의 텐서와 NumPy배열은 메모리 공간을 공유하기 떄문에, 하나를 변경하면 다른 하나도 변경됩니다.

텐서를 NumPy 배열로 변환하기

In [ ]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


- 텐서의 변경사항이 NumPy 배열에 반영됩니다.

In [ ]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


NumPy 배열을 텐서로 변환하기

In [ ]:
n = np.ones(5)
t = torch.from_numpy(n)

In [ ]:
np.add(n,1,out = n)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
n: [2. 2. 2. 2. 2.]
